# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

In [2]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [7]:
A = np.ones(100)
print(A)
A = np.array([1. for i in range(100)])
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Create a vector with values ranging from 10 to 49

In [9]:
U = np.array([i+10 for i in range(40)])
print(U)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [10]:
U = np.array([i/5 for i in range(5)])
print(U)

[0.  0.2 0.4 0.6 0.8]


Convert a float array into an integer array in place

In [12]:
U=np.array([5.,6.,2.5,3.8,3.14,9.58])
print(U)
V=U.astype(int)
print(V)

[5.   6.   2.5  3.8  3.14 9.58]
[5 6 2 3 3 9]


Given a boolean array

- return the indices where 
- negate the array inplace? 

In [75]:
U = np.array([True, False, False, True, True, True, False, True])
print(U)
print(np.argwhere(U))

print(np.where(U == False,True,False))

[ True False False  True  True  True False  True]
[[0]
 [3]
 [4]
 [5]
 [7]]
[False  True  True False False False  True False]


Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [111]:
U=np.array([1,2,3,4,5,6])
V=np.array([7,8,9,10,11,12])
print(np.dot(U,V))
print(np.inner(U,V))

tU = np.reshape(U,(-1,1))
tV = np.reshape(V,(-1,1))
print(np.outer(U,V))
print(np.dot(tU,tV.T))

M = tU.T + tV
print(M)
M=np.add.outer(U,V)
print(M)

217
217
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
[[ 8  9 10 11 12 13]
 [ 9 10 11 12 13 14]
 [10 11 12 13 14 15]
 [11 12 13 14 15 16]
 [12 13 14 15 16 17]
 [13 14 15 16 17 18]]
[[ 8  9 10 11 12 13]
 [ 9 10 11 12 13 14]
 [10 11 12 13 14 15]
 [11 12 13 14 15 16]
 [12 13 14 15 16 17]
 [13 14 15 16 17 18]]


Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [117]:
M=[ [0,1,2],
    [3,4,5],
    [6,7,8] ]
print(M[1][1])

M=np.array(M)
print(M)
print(M[1][1])
M=np.arange(9).reshape(3,3)
print(M)
print(M[1,1])

#M[[1,0]] = M[[0,1]]
#print(M)

#print(M[1:,1:])
#print(M[np.ix_([1,2],[1,2])])
#print(np.array([M[1][1:],M[2][1:]]))

print(np.diag(M))
#print([M[i][i] for i in range(len(M))])

print(M@M@M)
#print(np.dot(np.dot(M,M),M))

V=np.array(range(3))
print(np.dot(V,M))

N=np.array(range(12)).reshape(3,4)
print(M@N)

print(M.reshape(1,-1))
print((M.T).reshape(1,-1))


V = np.array([1,2,3])

print(V*M[:,None])
print((V*(M.T)[:,None]).T)

4
[[0 1 2]
 [3 4 5]
 [6 7 8]]
4
[[0 1 2]
 [3 4 5]
 [6 7 8]]
4
[0 4 8]
[[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]
[15 18 21]
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]]
[[0 1 2 3 4 5 6 7 8]]
[[0 3 6 1 4 7 2 5 8]]
[[[ 0  2  6]]

 [[ 3  8 15]]

 [[ 6 14 24]]]
[[[ 0  1  2]]

 [[ 6  8 10]]

 [[18 21 24]]]


Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [127]:
def is_symmetric(M):
    assert len(M) == len(M[0])
    return (M.T == M).all()

print(is_symmetric(M))
N = np.array([[1,2,3],
              [2,4,5],
              [3,5,8]])
print(is_symmetric(N))

False
True


## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

In [125]:
from lab2.utils import get_random_number_generator

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

In [151]:
seed = 150
rng = get_random_number_generator(seed)

nb_trials = 100000
Dis1 = np.array([np.random.binomial(1,.4) for i in range(nb_trials)])
nb_success = np.random.binomial(1000,.4)
print(Dis1.mean())
print(Dis1.var())


0.39765
0.2395244775


Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column